export const GET_PHOTO_REQUEST = 'GET_PHOTO_REQUEST'
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS'
export const GET_PHOTO_FAILURE = 'GET_PHOTO_FAILURE'

export const GET_ALBUM_REQUEST = 'GET_ALBUM_REQUEST'
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS'
export const GET_ALBUM_FAILURE = 'GET_ALBUM_FAILURE'

export const GET_ALBUM_PHOTO_BY_ID_REQUEST = 'GET_ALBUM_PHOTO_BY_ID_REQUEST'
export const GET_ALBUM_PHOTO_BY_ID_SUCCESS = 'GET_ALBUM_PHOTO_BY_ID_SUCCESS'
export const GET_ALBUM_PHOTO_BY_ID_FAILURE = 'GET_ALBUM_PHOTO_BY_ID_FAILURE'

export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM'
export const SET_ALBUM_FILTERED = 'SET_ALBUM_FILTERED'
